[package]
name = "tuneorg"
version = "0.1.0"
authors = ["Karlis Lauva <karlis@karlis.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
id3 = "0.6.4"
